export const SET_PETS = 'SET_PETS'
export const SET_BREED = 'SET_BREED'
export const SET_ANIMAL = 'SET_ANIMAL'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'
export const SET_BREEDS = 'SET_BREEDS'